# Generated by Django 5.0 on 2023-12-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_alter_furniture_image_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='furnitures',
            field=models.ManyToManyField(blank=True, null=True, to='furniture.furniture'),
        ),
    ]
